# Generated by Django 5.0.2 on 2024-09-05 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursemodel",
            name="description",
            field=models.CharField(max_length=100),
        ),
    ]
