# Generated by Django 5.0.2 on 2024-09-05 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0003_registrationmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentmodel",
            name="cpf",
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
