# Generated by Django 5.0.2 on 2024-09-06 11:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0004_alter_studentmodel_cpf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursemodel",
            name="code",
            field=models.CharField(
                max_length=10,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(5)],
            ),
        ),
    ]
