# Generated by Django 5.0.2 on 2024-09-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0005_alter_coursemodel_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentmodel",
            name="email",
            field=models.EmailField(max_length=100),
        ),
    ]
